# Generated by Django 4.0.3 on 2022-04-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_acervo', '0003_usuario_rename_modelofilme_filme_acervo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acervo',
            old_name='titulo',
            new_name='filme',
        ),
    ]
