# Generated by Django 4.0.3 on 2022-04-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_acervo', '0006_rename_filme_id_acervo_filme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='Descricao',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='rating',
        ),
        migrations.AddField(
            model_name='acervo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acervo',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
