# Generated by Django 4.0.3 on 2022-04-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_acervo', '0007_remove_filme_descricao_remove_filme_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acervo',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='acervo',
            name='rating',
        ),
        migrations.AddField(
            model_name='filme',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
