# Generated by Django 4.0.3 on 2022-04-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTeste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloFilme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('Descricao', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.DeleteModel(
            name='ModeloTeste',
        ),
    ]
