# Generated by Django 4.0.3 on 2022-04-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appTeste', '0002_modelofilme_delete_modeloteste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='ModeloFilme',
            new_name='Filme',
        ),
        migrations.CreateModel(
            name='Acervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTeste.usuario')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTeste.filme')),
            ],
        ),
    ]
