# Generated by Django 4.0.3 on 2022-04-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTeste', '0004_rename_titulo_acervo_filme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acervo',
            old_name='filme',
            new_name='filme_id',
        ),
        migrations.RenameField(
            model_name='acervo',
            old_name='nome',
            new_name='usuario_id',
        ),
    ]
