# Generated by Django 4.0.3 on 2022-04-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTeste', '0009_filme_foto_alter_filme_titulo_alter_usuario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='acervo',
            name='review_do_usuario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
